apiVersion: batch/v1
kind: CronJob
metadata:
  name: uptimerobot-updater
spec:
  schedule: "*/60 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: api-service-account 
          containers:
          - name: uptimerobot-updater
            image: registry.tino.sh/ingress-uptime
            envFrom:
            - secretRef:
              name: API
            command: ["node", "index.js"]
          restartPolicy: OnFailure
