apiVersion: batch/v1
kind: CronJob
metadata:
  name: uptimerobot-updater
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1000
      template:
        spec:
          serviceAccountName: api-service-account
          containers:
          - name: uptimerobot-updater
            image: registry.tino.sh/ingress-uptime
            env:
              - name: API
                valueFrom:
                  secretKeyRef:
                    name: api-uptimerobot
                    key: API
            command: ["npm", "start"]
          restartPolicy: Never
